apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: hubipi-lh8m6
  name: hubipi-lh8m6-storage
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: hubipi-lh8m6
      machine.openshift.io/cluster-api-machineset: hubipi-lh8m6-storage
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: hubipi-lh8m6
        machine.openshift.io/cluster-api-machine-role: storage
        machine.openshift.io/cluster-api-machine-type: storage
        machine.openshift.io/cluster-api-machineset: hubipi-lh8m6-storage
        node-role.kubernetes.io/storage: ""
    spec:
      taints:
      - key: node-role.kubernetes.io/storage
        effect: NoSchedule
        value: "true"
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          cluster.ocs.openshift.io/openshift-storage: ""
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 32768
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: vlan_301
          numCPUs: 16
          numCoresPerSocket: 4
          snapshot: ""
          template: hubipi-lh8m6-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: Linkplus-Demo
            datastore: tpsw1_p1_d4
            folder: /Linkplus-Demo/vm/hubipi-lh8m6
            resourcePool: /Linkplus-Demo/host/lpvmw-cls/Resources
            server: tpvc3-67.lp.int
