---
- name: Generate htpasswd file to authenticate later to the registry
  command: htpasswd -bBc /tmp/myregistry/auth/htpasswd {{user}} {{password}}

- name: generate auth data for pull-secret.json file
  shell: echo -n "{{user}}:{{password}}" | base64 -w0
  register: username_password_base64
  
- name: "mkdir for root auth.json (based on an official solution https://access.redhat.com/solutions/5312991)"
  file:
    path: /run/containers/0
    state: directory

- name: Append dummy:dummy login for myregistry:5000 in /tmp/pull-secret.json
  command: "jq '.auths += {\"myregistry:5000\": {\"auth\": \"{{username_password_base64.stdout}}\"}}' /tmp/pull-secret.json"
  register: data

- name: generate auth.json
  copy:
    dest: /run/containers/0/auth.json
    content: |
      {{data.stdout}}
