---
- name: Generate htpasswd file to authenticate later to the registry
  command: htpasswd -bBc /tmp/myregistry/auth/htpasswd {{user}} {{password}}

- name: generate auth data for pull-secret.json file
  shell: echo -n "{{user}}:{{password}}" | base64 -w0
  register: username_password_base64
  
- name: append myregistry:5000 to pull-secret.json
  shell: "cat <<< $(jq -c '.auths += {\"myregistry:5000\": {\"auth\":\"{{ username_password_base64.stdout }}\"}}' /tmp/pull-secret.json) > /tmp/pull-secret.json"

- name: "mkdir for root auth.json (based on an official solution https://access.redhat.com/solutions/5312991)"
  file:
    path: /run/containers/0
    state: directory

- name: generate auth.json
  copy:
    dest: /run/containers/0/auth.json
    src: /tmp/pull-secret.json
    remote_src: yes

- name: Copy pull-secret.json
  template:
    src: pull-secret.json.j2
    dest: /tmp/myregistry/data/registry/pull-secret.json
