apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoringnfs
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs/pvs
    server: 192.168.0.40
