apiVersion: apps/v1
kind: Deployment
metadata:
  name: noisy
  namespace: logging-diagnose
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: noisy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: noisy
    spec:
      containers:
      - args:
        - --delay
        - 100ms
        image: quay.io/redhattraining/logger:v0.5
        imagePullPolicy: IfNotPresent
        name: noisy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
